services:
  - type: web
    name: sharp-crm-backend
    env: node
    repo: https://github.com/your-username/sharp-crm-aws-3
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: AWS_REGION
        value: us-east-1
    # Auto-deploy from main branch
    autoDeploy: true
    branch: main
    # Health check path
    healthCheckPath: /health
    # Build and deployment settings
    buildFilter:
      paths:
        - backend/**
    rootDir: backend
